version: 1

formatters:
    default:
        format: '%(asctime)s | %(levelname)-8s | %(name)-8s | %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    scheduler:
        format: '%(asctime)s | %(levelname)-8s | apscheduler | %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    default_extra:
        format: '%(asctime)s | %(levelname)-8s | %(name)-11s | %(message)s'
        datefmt: '%H:%M:%S'
    scheduler_extra:
        format: '%(asctime)s | %(levelname)-8s | apscheduler | %(message)s'
        datefmt: '%H:%M:%S'
handlers:
    file:
        formatter: default
        class: logging.handlers.RotatingFileHandler
        maxBytes: 10000
        backupCount: 3
        filename: logs/cave.log
        level: DEBUG
    filesched:
        formatter: scheduler
        class: logging.handlers.RotatingFileHandler
        maxBytes: 10000
        backupCount: 1
        filename: logs/schedule.log
        level: INFO
    filewarn:
        formatter: default
        class: logging.handlers.RotatingFileHandler
        maxBytes: 10000
        backupCount: 1
        filename: logs/warn.log
        level: WARNING
    console:
        formatter: default
        class: logging.StreamHandler
        stream: ext://sys.stdout
        level: INFO
    file_extra:
        formatter: default_extra
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        interval: 1
        filename: logs/extra.log
        level: DEBUG
        backupCount: 2
    filesched_extra:
        formatter: scheduler_extra
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        interval: 1
        filename: logs/extra.log
        level: DEBUG
        backupCount: 2
loggers:
#    default:
#        level: DEBUG
#        handlers: [file, console]
    apscheduler:
        level: DEBUG
        handlers: [filesched, filesched_extra]
    werkzeug:
        level: DEBUG
        handlers: [console, file, file_extra]
    cave:
        level: DEBUG
        handlers: [file, console, file_extra]
    cave server:
        level: DEBUG
        handlers: [file, console, file_extra]
    cave client:
        level: DEBUG
        handlers: [file, console, file_extra]
#    root:
#        level: DEBUG
#        handlers: [console, file, file_extra]
#    flask:
#        level: DEBUG
#        handlers: [console, file, file_extra]
    flask.app:
        level: DEBUG
        handlers: [console, file, file_extra]
